export const RECEIVE_ARTICLS = 'RECEIVE_ARTICLS';
export const RECEIVE_ARTICLES_DETAILS = 'RECEIVE_ARTICLES_DETAILS';
export const RECEIVE_CATEGORIES='RECEIVE_CATEGORIES'
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';

